### ISSUE TITLE
Backend auth/account endpoints

### ISSUE THREAD

**Issue by ingemar-cpr** [climatepolicyradar/navigator#415]
Full spec: https://docs.google.com/document/d/1X2TRIZYdYdLiQH1HlZpmTcOa4nf5LLh2fXfcoR8Ns-s/edit#

POST: /activations/{id}
Used by user to set their password and accept invitation
Body: password

POST: /v1/tokens
Used for signing in to CPR. Should return a JWT token if successful or throw 401 if unsuccessful. No details of failure should be returned to user.
Body: email, password

DELETE: /v1/passwords
Request a password to be reset. Should send an email to the user with a link to verify email.
Body: email

POST :/v1/passwords
Set the new reset password. Send email confirmation.
Body: password, resetToken

DELETE: /v1/emails
Request the email to be updated. Until verified, the email will not be updated. Potential implementation would be to save the new email temporarily in the token so once it's verified, it will be available to use.
Body: email

PUT: /v1/emails
Update the email for signed in users. Send email confirmation.
Body: email, emailToken

POST: /v1/accounts
Sign up a new account. For Alpha, it will be the submission from the invite link.
Body: password, invitationToken

PUT: /v1/accounts
Update my account details. Send email confirmation.
Body: account

DELETE: /v1/accounts
Delete my account.

**Comment by opyate** [comment]
For password reset flow, see https://github.com/climatepolicyradar/navigator/issues/283

**Comment by eurolife** [comment]
@opyate @ingemar-cpr We will need to agree on what fields will be included in a user account. In the cookie cutter api these already exist:

- first_name
- last_name
- email
- is_active
- is_superuser
- id

I think the above are okay except since we are currently collecting Full name with both first and last name in one field, we should combine the first and last name fields. Also could add these fields:

- Affiliation/Organisation (free text)
- Affiliation type (these can be multiple)
- Policy type of interest (these can be multiple)
- Geographical scope (these can be multiple)
- Data focus of interest (these can be multiple)
